### PR TITLE
creates index.html with yoti script, installs basic dependencies

### LINKED ISSUE #6: Initialise project with index.html and npm packages
We are going to use hapi

### PR DESCRIPTION
**Pull request by emilyb7**
resolves #6

### CODE REVIEW

**Comment by jsms90** [comment]
@emilyb7 Please reference an issue with each of your commits :+1: 

Either
use git reset and recommit
or do an interactive rebase
With `git reset`

Once you have recommit with issue numbers attached to commit messages you will need to force push

See https://github.com/CYPIAPT-LNDSE/goals-app/issues/22#issue-204266922

**Comment by emilyb7** [comment]
eoin was not this mean

**Comment by jsms90** [comment]
@emilyb7 

This is exactly what Eoin has asked me to be strict on:
https://github.com/CYPIAPT-LNDSE/anxiety-ladder/pull/61#issuecomment-276906329

**Comment by des-des** [comment]
Hehe

**Pull request closed without merging**
